#!/bin/bash

#
# autokill -- automatically kill the DCS server if the coop engine 
#             has crashed.
#
#             Should be run from the DCS Logs directory
#

# Time in seconds that log files must be unchanged to autokill
THRESHOLD=300

# Interval between checks (seconds)
SLEEP=180


Kill_DCS()
        {
        DCS_PID=`ps -ef | grep DCS_server | awk '{print $2}'`

        # Only send kill if server is running
        if [ -f ../dcs.lock ]
                then
                echo "killing DCS_server.exe PID $DCS_PID"
                kill $DCS_PID
        fi

        #taskkill /IM DCS_server.exe
        sleep 20
        }


while [ 1 ]
        do
        # Get current time
        NOW_EPOCH=`date +%s`
        NOW_DATE=`date`

        # Get staleness of bfnext.txt
        FILE_EPOCH=`stat --format='%Y' bfnext.txt`

        # Get server runtime
        SERVER_START_EPOCH=`stat --format='%W' ../dcs.lock`

        STALENESS=`expr $NOW_EPOCH \- $FILE_EPOCH`
        SERVER_RUNTIME=`expr $NOW_EPOCH \- $SERVER_START_EPOCH`

        if [ $STALENESS -gt $THRESHOLD ]
                then
                echo "${NOW_DATE}: Runtime ${SERVER_RUNTIME} s : DCS stale for $STALENESS seconds; want to kill."
                Kill_DCS
        else
                echo "${NOW_DATE}: Runtime ${SERVER_RUNTIME} s : DCS stale for only $STALENESS seconds; keep running."
        fi

        sleep $SLEEP
        done

