#!/bin/bash
#
# Postprocess the base mission file and templates to build the complete final .miz to run the actual scenario
# 

 ../bfnext/bftools/bftools.exe miz --output SouthAtlantic_final.miz --base SouthAtlantic_base.miz --weapon templates/weapon.cauc80s.miz --warehouse templates/warehouse.cauc80s.miz --options SouthAtlantic_base.miz

