#!/bin/bash
#
# Postprocess the base mission file and templates to build the complete final .miz to run the actual scenario
# 

 ../bfnext/bftools/bftools.exe miz --output sa2_final.miz --base sa2_base.miz --weapon templates/weapons.sa2.miz --warehouse templates/warehouse.sa2.empty.miz --options templates/options.sa2.miz

#../bfnext/bftools/bftools.exe miz --output sa2_final.miz --base sa2_base.miz --weapon templates/weapons.sa2.miz --options templates/options.sa2.miz


