#!/bin/bash
#
# Postprocess the base mission file and templates to build the complete final .miz to run the actual scenario
# 

 ../../bfnext/bftools/bftools.exe miz --output afghanistan.miz --base afghan_base.miz --weapon templates/weapons.miz --warehouse templates/warehouse.miz --options templates/options.miz

#../bfnext/bftools/bftools.exe miz --output sa2_final.miz --base sa2_base.miz --weapon templates/weapons.sa2.miz --options templates/options.sa2.miz


