#!/bin/bash
#
# Postprocess the base mission file and templates to build the complete final .miz to run the actual scenario
# 

 ../../bfnext/bftools/bftools.exe miz --output afghanistan_v4.miz --base afghan_base_v4.miz --weapon templates/weapons.miz --warehouse templates/warehouse.miz --options templates/options.miz
